-- generated: Sat Dec 24 20:44:52 JST 2011
import qualified Tct.Processor as P
import qualified Tct.Processor.Standard as S
import qualified Tct.Method.Predicates as Preds
import Tct.Processor.Timeout (timeoutProcessor)
import Tct.Method.PopStar (popstarProcessor)
import Tct.Method.PopStar (ppopstarProcessor)
import Tct.Method.PopStar (lmpoProcessor)
import Tct.Method.Bounds (boundsProcessor)
import Tct.Method.Combinator (failProcessor)
import Tct.Method.Combinator (successProcessor)
import Tct.Method.Combinator (emptyProcessor)
import Tct.Method.Combinator (openProcessor)
import Tct.Method.Combinator (iteProcessor)
import Tct.Method.Combinator (bestProcessor)
import Tct.Method.Combinator (fastestProcessor)
import Tct.Method.Combinator (sequentiallyProcessor)
import Tct.Method.EpoStar (epostarProcessor)
import Tct.Method.Matrix.NaturalMI (matrixProcessor)
import Tct.Method.Matrix.ArcticMI (arcticProcessor)
import Tct.Method.Poly.NaturalPI (polyProcessor)
import Tct.Method.InnermostRuleRemoval (irrProcessor)
import Tct.Method.ComposeRC (composeRCProcessor)
import Tct.Method.Weightgap (weightgapProcessor)
import Tct.Method.Compose (composeProcessor)
import Tct.Method.DP.DependencyPairs (dependencyPairsProcessor)
import Tct.Method.DP.Simplification (removeTailProcessor)
import Tct.Method.DP.Simplification (simpDPRHSProcessor)
import Tct.Method.DP.Simplification (simpKPProcessor)
import Tct.Method.DP.UsableRules (usableRulesProcessor)
import Tct.Method.DP.PathAnalysis (pathAnalysisProcessor)
import Tct.Method.Uncurry (uncurryProcessor)
